tomcat:
  image: tomcat
  ports:
    - "8080:8080"
  environment:
    VIRTUAL_HOST: tomcat
  volumes:
    - "./target/spring-mvc-hibernate-xml.war:/usr/local/tomcat/webapps/app.war"
  links:
    - db

db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: PersonDB
  container_name: db
  volumes:
    - "./db:/docker-entrypoint-initdb.d"
